version: '3.9'
services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/app
    restart: always
    command: >
      sh -c "cd src/ &&
             python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py test &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - ENV=container
      - DB_NAME=finances_db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_PORT=5432
      - DB_HOST=db
      - DEBUG=true
      - SECRET_KEY=a98suf20qw90skpcka0coqw-0kc0ve8hvcjwq09c
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=finances_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres