version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/app
    command: >
      sh -c "cd src/ &&
             python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py test &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=finances_db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_PORT=5432
      - SECRET_KEY=asdfjwbqiuo
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=finances_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres