# Generated by Django 3.2.9 on 2021-12-15 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_alter_operation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account', to='finances.accountcategory'),
        ),
    ]
